language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper # for Qt5
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa # for Qt5
  - sudo apt-get update
  - sudo apt-get install -qq ubuntu-sdk libc6:i386 libgstreamer-plugins-base0.10 libgstreamer-plugins-base0.10-dev
script:
  - qmake QMAKE_CXX=$CXX hamcrest-qt.pro
  - make         
  - make check