language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper # for Qt5
  - sudo apt-get update
  - sudo apt-get install -qq qtbase5-dev qtchooser
script:
  - qtchooser -run-tool=qmake -qt=qt5
  - make
  - export LD_LIBRARY_PATH="../../core:$LD_LIBRARY_PATH"         
  - make check